const ContestActionTypes = {
  FETCH_CONTESTS_START: "FETCH_CONTESTS_START",
  FETCH_CONTESTS_SUCCESS: "FETCH_CONTESTS_SUCCESS",
  FETCH_CONTESTS_FAILURE: "FETCH_CONTESTS_FAILURE",
};

export default ContestActionTypes;
